### ISSUE TITLE
Log in and name order

### ISSUE THREAD

**Issue by LAGreg1234** [Sycration/CZ4R#10]
Jessica cannot log in.
Make the signing list non-scrolling

**Comment by Sycration** [comment]
here's the culprit
https://github.com/Sycration/CZ4R/blob/8bca6a0d8a900dd941b8eef0baf92cac288700db/src/login.rs#L76
it only sends the user to the redirect page if the encrypted password is blank, which is never the case

**Comment by Sycration** [comment]
Completed
