### ISSUE TITLE
Search feature

### ISSUE THREAD

**Issue by LAGreg1234** [Sycration/CZ4R#7]
The admin and the employee need to be able to search all past jobs by the following fields:
Site Name
Job Date
Work Order
Service Code
Address
FIELD NOTES
It would be ideal if this could be it's own tab
Home - Job List - Search - Admin panel

Please have the date field default to empty.

**Comment by Sycration** [comment]
Addressed in https://github.com/Sycration/CZ4R/commit/0f2f9705ded856d97147c1746c3654070e01170e

**Comment by Sycration** [comment]
long stale issue
